/**
 * @author Juveria-Manzar
 * @email juveriamanzar29@gmail.com
 * @create date 2020-02-22 14:23:47
 * @modify date 2020-02-22 14:23:47
 * @desc Core Module:net
 */
const net = require('net')

const server = net.createServer()
const connectedClients = []

server.listen({
    host: 'localhost',
    port: 8080
})

//connection is the event generated by server 

server.on('connection', (client) => {
    console.log("client connected")
    client.write("Welcome to the server")
    connectedClients.push(client)
})

setInterval(() => {
    const now = new Date().toISOString();
    connectedClients.forEach(client => {
        client.write(now)
    });
}, 2000)